site_name: HypoTremorMCMC

nav:
  - Home: index.md
  - Usage:
    - hypo_tremor_convert.md
    - hypo_tremor_correlate.md
    - hypo_tremor_measure.md
    - hypo_tremor_select.md
    - hypo_tremor_mcmc.md
    - hypo_tremor_statistics.md
  - Need to prepare:
    - parameter_file.md
    - station_file.md

theme: readthedocs

markdown_extensions:
  - mdx_math
  - admonition
    
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
