site_name: HypoTremorMCMC

nav:
  - Usage:
    - hypo_tremor_convert.md
    - hypo_tremor_correlate.md
    - hypo_tremor_measure.md
  - Data preparation:
    - parameter_file.md
    - station_file.md

theme: readthedocs

markdown_extensions:
  - mdx_math
  - admonition
    
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
