name: Fortran Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: centos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo yum update -y
          sudo yum install -y gcc-gfortran openmpi-devel fftw3-devel

      - name: Move to src directory and build
        working-directory: src
        run: |
          make FFTW="-I/usr/include -L/usr/lib64 -lfftw3"
